# Generated by Django 2.0.2 on 2018-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortner',
            fields=[
                ('short_id', models.SlugField(max_length=8, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
